# Generated by Django 3.1.5 on 2021-01-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_mode', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DreamTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('pictures', models.ImageField(upload_to='blog/uploads')),
                ('journey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.journey')),
            ],
        ),
    ]
