# Generated by Django 3.1.5 on 2021-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dreamtrip_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamtrip',
            name='pictures',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
