# Generated by Django 3.1.5 on 2021-01-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamtrip',
            name='budget',
            field=models.IntegerField(verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='dreamtrip',
            name='city_name',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dreamtrip',
            name='journey_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.journey', verbose_name='Journey Mode'),
        ),
        migrations.AlterField(
            model_name='dreamtrip',
            name='pictures',
            field=models.ImageField(upload_to='gallery', verbose_name='Pictures'),
        ),
        migrations.AlterField(
            model_name='dreamtrip',
            name='story',
            field=models.CharField(max_length=100, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='dreamtrip',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Visitor'),
        ),
    ]
